[package]
name = "backend"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.7.5"
tokio = { version = "1.38", features = ["full"] }
sqlx = { version = "0.7.4", features = ["runtime-tokio-native-tls", "mysql", "chrono"] }
serde = { version = "1.0.203", features = ["derive"] }
serde_json = "1.0.120"
dotenvy = "0.15.7"
tower-http = { version = "0.6", features = ["cors", "trace"] }
reqwest = { version = "0.12.5", default-features = false, features = ["json", "rustls-tls"] }
chrono = { version = "0.4.38", features = ["serde"] }
sha2 = "0.10.8"
hex = "0.4.3"
validator-engine = { path = "validator" }
base64 = "0.22"
