[package]
name = "agent_network"
version = "0.1.0"
edition = "2021"

[dependencies]
odra = { version = "=2.8.2", features = [], default-features = false }
odra-modules = { version = "=2.8.2", default-features = false }
odra-casper-livenet-env = { version = "=2.8.2", optional = true }
env_logger = { version = "0.10.2", optional = true }

[dev-dependencies]
odra-test = { version = "=2.8.2", features = [], default-features = false }

[build-dependencies]
odra-build = { version = "=2.8.2", features = [], default-features = false }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
odra-build = { version = "=2.8.2", features = [], default-features = false }
odra-cli = { version = "=2.8.2", features = [], default-features = false }

[features]
default = []
livenet = ["odra-casper-livenet-env", "dep:env_logger"]

[[bin]]
name = "agent_network_build_contract"
path = "bin/build_contract.rs"
test = false

[[bin]]
name = "agent_network_build_schema"
path = "bin/build_schema.rs"
test = false

[[bin]]
name = "agent_network_cli"
path = "bin/cli.rs"
test = false

[[bin]]
name = "agent_network_livenet"
path = "bin/livenet_deploy.rs"
required-features = ["livenet"]
test = false

[[bin]]
name = "agent_network_register"
path = "bin/register_agent.rs"
required-features = ["livenet"]
test = false

[[bin]]
name = "agent_network_submit_complete"
path = "bin/submit_complete.rs"
required-features = ["livenet"]
test = false

[[bin]]
name = "agent_network_submit_result"
path = "bin/submit_result.rs"
required-features = ["livenet"]
test = false

[[bin]]
name = "agent_network_submit_validation"
path = "bin/submit_validation.rs"
required-features = ["livenet"]
test = false

[[bin]]
name = "agent_network_finalize_task"
path = "bin/finalize_task.rs"
required-features = ["livenet"]
test = false

[[bin]]
name = "agent_network_decay_reputation"
path = "bin/decay_reputation.rs"
required-features = ["livenet"]
test = false

[[bin]]
name = "agent_network_update_metadata"
path = "bin/update_metadata.rs"
required-features = ["livenet"]
test = false

[[bin]]
name = "agent_network_register_validator"
path = "bin/register_validator.rs"
required-features = ["livenet"]
test = false

[[bin]]
name = "agent_network_stake_agent"
path = "bin/stake_agent.rs"
required-features = ["livenet"]
test = false

[[bin]]
name = "agent_network_stake_validator"
path = "bin/stake_validator.rs"
required-features = ["livenet"]
test = false

[profile.release]
codegen-units = 16
lto = "thin"

[profile.dev.package."*"]
opt-level = 3
